language: clojure
lein: lein2
script: lein2 uberjar
services:
  - redis-server
after_success:
  - cp .travis/known_hosts ~/.ssh/known_hosts
  - chmod 600 ~/.ssh/known_hosts
  - chmod 600 .travis/id_rsa
  - chmod 600 .travis/id_rsa.pub
  - ssh-add .travis/id_rsa
  - scp -i .travis/id_rsa target/wiki-1.0-standalone.jar root@docs.anychart.com:/apps/wiki/wiki-1.0-standalone.jar
  - ssh root@docs.anychart.com "supervisorctl restart wiki"
