language: clojure
lein: lein2
script: lein2 uberjar
branches:
  only:
  - master
  - staging
services:
  - redis-server
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then export SERVER="docs.anychart.com"; fi
  - if [ "$TRAVIS_BRANCH" == "staging" ]; then export SERVER="104.236.109.246"; fi
  - echo "Deploying to $SERVER"
  - cp .travis/known_hosts ~/.ssh/known_hosts
  - chmod 600 ~/.ssh/known_hosts
  - chmod 600 .travis/id_rsa
  - chmod 600 .travis/id_rsa.pub
  - ssh-add .travis/id_rsa
  - scp -i .travis/id_rsa target/uberjar/wiki-1.1-standalone.jar root@$SERVER:/apps/wiki/wiki-1.1-standalone.jar
  - ssh root@$SERVER "supervisorctl restart wiki"
notifications:
  slack: anychart-team:sJRPhNn8Ur8yVdhvhgp6EbDM
