language: clojure
jdk:
  - openjdk8
script: lein uberjar
sudo: false
branches:
  only:
  - master
  - staging
  - bible
cache:
  directories:
  - "$HOME/.m2"
services:
- redis-server
before_install:
- openssl aes-256-cbc -K $encrypted_b78600e252ed_key -iv $encrypted_b78600e252ed_iv -in .travis/id_rsa.enc -out id_rsa -d
- mv id_rsa ~/.ssh/id_rsa
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then export APP="docs-prod"; fi
- if [ "$TRAVIS_BRANCH" == "staging" ]; then export APP="docs-stg"; fi
- if [ "$TRAVIS_BRANCH" == "bible" ]; then export APP="bible-stg"; fi
- echo "Deploying to $SERVER"
- mv .travis/known_hosts ~/.ssh/known_hosts
- mv .travis/id_rsa.pub ~/.ssh/id_rsa.pub
- chmod 400 ~/.ssh/known_hosts
- chmod 400 ~/.ssh/id_rsa
- chmod 400 ~/.ssh/id_rsa.pub
- ssh-add ~/.ssh/id_rsa
- scp target/uberjar/wiki-2.0-standalone.jar root@104.236.66.244:/apps/$APP/docs-2.0-standalone.jar
- scp target/uberjar/wiki-2.0-standalone.jar root@104.131.17.78:/apps/$APP/docs-2.0-standalone.jar
- ssh root@104.236.66.244 "supervisorctl restart $APP"
- ssh root@104.131.17.78 "supervisorctl restart $APP"

notifications:
  webhooks:
    urls:
      - ${webhook_url}
    on_start: always
    on_success: always
    on_failure: always
    on_error: always
