language: clojure
script: lein uberjar
sudo: false
branches:
  only:
  - master
  - staging
cache:
  directories:
  - $HOME/.m2
services:
- redis-server
before_install:
  - openssl aes-256-cbc -K $encrypted_831d2a0628ae_key -iv $encrypted_831d2a0628ae_iv -in id_rsa.enc -out id_rsa -d
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then export APP="docs-prod"; fi
- if [ "$TRAVIS_BRANCH" == "staging" ]; then export APP="docs-stg"; fi
- echo "Deploying to $SERVER"
- cp .travis/known_hosts ~/.ssh/known_hosts
- chmod 600 ~/.ssh/known_hosts
- chmod 600 .travis/id_rsa
- chmod 600 .travis/id_rsa.pub
- ssh-add .travis/id_rsa
- scp -i .travis/id_rsa target/uberjar/wiki-2.0-standalone.jar root@104.236.66.244:/apps/$APP/docs-2.0-standalone.jar
- scp -i .travis/id_rsa target/uberjar/wiki-2.0-standalone.jar root@104.131.17.78:/apps/$APP/docs-2.0-standalone.jar
- ssh root@104.236.66.244 "supervisorctl restart $APP"
- ssh root@104.131.17.78 "supervisorctl restart $APP"
notifications:
  slack: anychart-team:sJRPhNn8Ur8yVdhvhgp6EbDM
