language: clojure
script: lein uberjar
sudo: false
branches:
  only:
  - master
  - staging
  - bible
cache:
  directories:
  - "$HOME/.m2"
services:
- redis-server
before_install:
- openssl aes-256-cbc -K $encrypted_b78600e252ed_key -iv $encrypted_b78600e252ed_iv -in .travis/id_rsa.enc -out id_rsa -d
- mv id_rsa ~/.ssh/id_rsa
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then export APP="docs-prod"; fi
- if [ "$TRAVIS_BRANCH" == "staging" ]; then export APP="docs-stg"; fi
- if [ "$TRAVIS_BRANCH" == "bible" ]; then export APP="bible-stg"; fi
- echo "Deploying to $SERVER"
- mv .travis/known_hosts ~/.ssh/known_hosts
- mv .travis/id_rsa.pub ~/.ssh/id_rsa.pub
- chmod 400 ~/.ssh/known_hosts
- chmod 400 ~/.ssh/id_rsa
- chmod 400 ~/.ssh/id_rsa.pub
- ssh-add ~/.ssh/id_rsa
- scp target/uberjar/wiki-2.0-standalone.jar root@104.236.66.244:/apps/$APP/docs-2.0-standalone.jar
- scp target/uberjar/wiki-2.0-standalone.jar root@68.183.148.118:/apps/$APP/docs-2.0-standalone.jar
- ssh root@104.236.66.244 "supervisorctl restart $APP"
- ssh root@68.183.148.118 "supervisorctl restart $APP"
notifications:
  slack:
    secure: GlKpceHLcrwqZ/k3hhYyAkZEE/g6Hrv/I7XwEebXt3sCExalhHP8kDDtQdEJuDlo7juz7c8yN14PCb7QBOJoYs64YR1JhYz4BNGpp4BTdEs3W22rzGJEpmrJNIL2M4YeC5st0F8tmDTcgfL/lt2yiIjyZEXrxmkg0r1HW3OP8F8=
